title: Nordplaner ApS
description: Website for Nordplaner ApS

baseurl: /
url: https://nordplaner.github.io

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
